### ISSUE TITLE
Create a new directory to place the document of SCI protocol definition and keep updated

### ISSUE THREAD

**Issue by Liurunyuan** [lrtjohn/J150#6]
@lrtjohn 
1. Please create a directory in this repo, you can name it "doc" or anything you like.
1. Then place the newest **SCI protocol document** in this directory.
1. Keep updated once the protocol is changed.

This could help me to update the SCI protocol function.

**Comment by Liurunyuan** [comment]
@lrtjohn 
You can also create a issue here and assign it to me when you find any bugs or improvement in the code, question is also fine.

**Comment by Liurunyuan** [comment]
I saw you send some discussion about SCI protocol in the WeChat, so it would be nice to update all the new changes in the SCI protocol document

**Comment by lrtjohn** [comment]
Software specs uploaded, check lasted GIT version
